### ISSUE TITLE
error: js-file-downloader.js:245 Refused to get unsafe header "Content-Disposition"

### ISSUE THREAD

**Issue by JamesQ-007** [AleeeKoi/js-file-downloader#1]
when I used this package to download file, it says that Refused to get unsafe header "Content-Disposition.

so How can I fix this problem ? thanks

**Comment by AleeeKoi** [comment]
Hello,
There is a browser protection that don't let you to download a file relative to an URL "http://aaa.com/..." if  your application run on domain "http://bbb.com".
Is this your case?
Thank you

**Comment by phuze** [comment]
First, i'll note that the author is attempting to get the filename by parsing the value of the `Content-Disposition` header ([refer to index.js#114:132](https://github.com/AleeeKoi/js-file-downloader/blob/master/src/index.js#L114-L132)).

Understanding that, you have two options.

1. If you control the server you're downloading from, you can resolve this issue by adding the header `Access-Control-Expose-Headers` with a value of `Content-Disposition` to your HTTP response.
2. Alternatively, if you don't control the server, you can avoid this error by passing a filename in the options, which will bypass the attempt to get the filename from the header.

```js
let downloadOptions = {
    url: 'https://example.domain.com/batman.jpg',
    filename: 'batman.jpg',
}
new JsFileDownloader(downloadOptions)
    .then(function() {
        console.log('download finished!')
    })
```
