### ISSUE TITLE
error 406

### ISSUE THREAD

**Issue by vicanfon** [AleeeKoi/js-file-downloader#10]
I am trying to download a zip file from gitlab using your library but I am getting a 406 error.

What could be the problem?

**Comment by AleeeKoi** [comment]
Hello @vicanfon ,
Please can you write here headers (request and response both) and your code?
Thank you

**Comment by AleeeKoi** [comment]
Hi @vicanfon , in the absence of an answer, I close the report. 
Let me know if you need more support.
