### ISSUE TITLE
URL-encoded filenames not un-encoded

### ISSUE THREAD

**Issue by micthiesen** [AleeeKoi/js-file-downloader#11]
Our server returns url-encoded filenames in the `Content-Disposition` header for compatibility reasons (e.g. to support accented characters). If our header looks like this:
```
Content-Disposition: attachment; filename="MetLife%20MET%20US.xlsx"; filename*=UTF-8''MetLife%20MET%20US.xlsx
```
the library downloads the file as:
```
MetLife%20MET%20US.xlsx
```

It would be great if the library un-encoded the filenames maybe using [decodeURIComponent()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/decodeURIComponent).

**Comment by AleeeKoi** [comment]
Hi @micthiesen!
I have made a new release introducing a callback for the file name.
In your case you could use it like:

```
new Downloader({ 
  ...,
  nameCallback: function(name) {
    return  decodeURIComponent(name);
  }
})
```

Let me know.

**Comment by micthiesen** [comment]
Nice thank you that’s perfect!
