### ISSUE TITLE
use the missing type under typescript

### ISSUE THREAD

**Issue by shusc24** [AleeeKoi/js-file-downloader#16]
Hi, this script is very good, it would be great if the library can add an d.ts file

**Comment by AleeeKoi** [comment]
Hi @shusc24 
Thank you!
TS is on my TODO list, I hope to do it soon! 🤞

**Comment by AleeeKoi** [comment]
Hi @shusc24 , added the index.d.ts file!
I'm refactoring the entire library using TS and release it in the next major release v2 (at now I need only to write tests).
Thank you!
