### ISSUE TITLE
Error status code

### ISSUE THREAD

**Issue by JacobSiegle** [AleeeKoi/js-file-downloader#18]
I don't see any way to get the status code from the error message thrown. Use case = 401 (Unauthorized) refresh users token and try again.

Looking a bit more into it the exceptions just might not be working correctly, the lib attempts to use -

https://github.com/AleeeKoi/js-file-downloader/blob/master/src/exception.js

Which then throws -

Error: Downloader error: TypeError: Cannot set property 'message' of undefined
    at XMLHttpRequest.request.onload (js-file-downloader.js:217)

Which prevents the error message from properly getting emitted out.

**Comment by AleeeKoi** [comment]
Hi @JacobSiegle check the new version v1.1.12
I have fix exception object and added as parameter of the thrown error "request" pointing the entire XMLHttpRequest object.
Let me now.

Thank you

**Comment by JacobSiegle** [comment]
Thanks for the fast turnaround, getting a new error now where the app won't compile anymore

ERROR in node_modules/js-file-downloader/index.d.ts:27:53 - error TS2314: Generic type 'Promise<T>' requires 1 type argument(s).

27   constructor(customParams: JsFileDownloaderProps): Promise<undefined,downloadException> | JsFileDownloader;
                                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
node_modules/js-file-downloader/index.d.ts:27:53 - error TS1093: Type annotation cannot appear on a constructor declaration.

27   constructor(customParams: JsFileDownloaderProps): Promise<undefined,downloadException> | JsFileDownloader;
                                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
node_modules/js-file-downloader/index.d.ts:27:92 - error TS2304: Cannot find name 'JsFileDownloader'.

27   constructor(customParams: JsFileDownloaderProps): Promise<undefined,downloadException> | JsFileDownloader;
                                                                                              ~~~~~~~~~~~~~~~~
node_modules/js-file-downloader/index.d.ts:28:12 - error TS2314: Generic type 'Promise<T>' requires 1 type argument(s).

28   start(): Promise<undefined,downloadException>;

**Comment by AleeeKoi** [comment]
Hi @JacobSiegle 
Please update to v1.1.13, I fixed the ts definition file.
I have not encountered any compilation problems, so let me know if errors persists (in this case let me know more about your project configuration, ecc.)
Thank you

**Comment by JacobSiegle** [comment]
Working great now thanks again for the quick turn around!
