### ISSUE TITLE
mobileDisabled is not used

### ISSUE THREAD

**Issue by gotson** [AleeeKoi/js-file-downloader#24]
There is a parameter `mobileDisabled` but it's not used anywhere in the code. Or did I miss something?

The code and doc would probably require clarification in regards to that parameter and `forceDesktopMode`, to clearly explain how to make it work on mobile.

For instance the doc mentions that `mobileDisabled`defaults to `false`, while it's `true` in the code. But anyhow this parameter is not used.

**Comment by AleeeKoi** [comment]
Hi @gotson ,
`mobileDisabled` was deprecated times ago.
Sorry, I need to fix it in the doc... 

Anyway, in mobile devices the library is disabled by default. You could set `forceDesktopMode = true` to activate also on mobile devices.

Thanks

**Comment by gotson** [comment]
Thanks, that's what I figured out from the code. You can keep this issue for updating the doc then 😉

**Comment by AleeeKoi** [comment]
Doc updated! 🤟
