### ISSUE TITLE
Content-Type should not bet set for GET-Requests 

### ISSUE THREAD

**Issue by k-a-z-u** [AleeeKoi/js-file-downloader#29]
request.setRequestHeader('Content-type', 'application/x-www-form-urlencoded');

sets a content-type for every request, even for GET requests where there is no Body, and thus no content-type.
https://stackoverflow.com/questions/5661596/do-i-need-a-content-type-header-for-http-get-requests

This causes issues for some REST-Frameworks and Firewalls, complaining about content-type being set without body.

**Comment by AleeeKoi** [comment]
Hi @k-a-z-u !
I will make it configurable in the next days, thanks!

**Comment by AleeeKoi** [comment]
Hi @k-a-z-u , please check the last release v.1.1.20
Thanks :)

**Comment by k-a-z-u** [comment]
Works like a charm!
Thank you very much :)
