### ISSUE TITLE
Fallback to new tab on CORS error

### ISSUE THREAD

**Issue by TheSharpieOne** [AleeeKoi/js-file-downloader#31]
I am running into #8, but it would be nice if this lib could better handle the CORS issue and fallback to the new tab approach

And/or allow one to specifically trigger the new tab approach; similar to, but the opposite of `forceDesktopMode`

**Comment by AleeeKoi** [comment]
Hi @TheSharpieOne 
It could be a nice feature, would you like to submit a PR?
Thank you.

**Comment by AleeeKoi** [comment]
Hi @TheSharpieOne 
Check the release v1.1.21
Thank you
