### ISSUE TITLE
Cannot set body on POST request.

### ISSUE THREAD

**Issue by copperfox777** [AleeeKoi/js-file-downloader#32]
Hello! 
Trying to get file, but i need to make a POST request with params. 
A pdf file will be generated with params, that must be send in post request, like name and so on.
```
new JsFileDownloader({
        url: process.env.REACT_APP_API_URL + url,
        headers: [{ name: "authorization", value: `Bearer ${token}` }],
        method: "POST",
        withCredentials: true,
        filename: "NDA.pdf",
        contentType: "application/json;charset=UTF-8",
      }) //@ts-ignore
        .catch(function (error) {
          console.dir("download error", error);
         
        });
```
Can you add a body field for POST request ?

**Comment by AleeeKoi** [comment]
Hi @copperfox777 !
This could be a very useful feature. 🚀
I'm unable to do this soon, do you want to send a PR?
Thanks

**Comment by AleeeKoi** [comment]
Hi @copperfox777 ,
Check the release v1.1.21
Thank you

**Comment by copperfox777** [comment]
Thank you! Very useful!
