### ISSUE TITLE
Append filename with mime type

### ISSUE THREAD

**Issue by marvin-kolja** [AleeeKoi/js-file-downloader#35]
Hey, I was wondering if you ever thought about appending the filename with the correct ending (e.g `.pdf`) following the mime type returned from the server. I implemented something like that with `js-file-download` but this package doesn't have type declarations.

Here a snippet:

```
axios
  .get(url, {
    responseType: 'blob',
  })
  .then((response) => response.data)
  .then((blob) => {
    // fileDownload is the function of the js-file-download library
    // It accepts the following: 
    // data: string | ArrayBuffer | ArrayBufferView | Blob,
    // filename: string,
    // mime?: string,
    // bom?: string
    fileDownload(blob, generateFilename(filename), blob.type);
  })
  .catch((error) => {
    console.error(error);
    throw error;
  });
```

The library does support a custom mime and what I did is just using the one which the blob reflects. Would be cool to have some ability to turn this on automatically.

What are your thoughts? Let me know 😉

**Comment by AleeeKoi** [comment]
Hi @marvin-kolja !
Thanks for your hint! It could be a nice feature.
I'm not able to implement it asap, so would you like to make a PR?
Let me know, thanks. 🚀

**Comment by marvin-kolja** [comment]
Sorry for the late response @AleeeKoi !

I was looking into this again and came up with two possible solutions:

1. Using the `content-type` response header to set the type.
   - This is pretty easy to set up but I don't know how secure it is. Imagine the server responses with a wrong type. This could result into security issues.
2. Using the `FileReader` and analyze the hex of the first 4 bytes of the file to gets its signature ([medium article](https://medium.com/the-everyday-developer/detect-file-mime-type-using-magic-numbers-and-javascript-16bc513d4e1e), [signature list](https://en.wikipedia.org/wiki/List_of_file_signatures))
   - This is pretty reliable, however, needs lots more code.

For now I think solution 2 is much better and I would start implementing it tomorrow. Would be cool to get your thoughts on this.

**Comment by AleeeKoi** [comment]
Hi @marvin-kolja ! Don't worry, yep `FileReader` is a good idea and it is well supported by browsers too.
I will look at your PR ASAP, I have another one to validate. I think I will make a new release in the next week.
Thank you! 🚀
