### ISSUE TITLE
CORS error in example

### ISSUE THREAD

**Issue by techieshark** [AleeeKoi/js-file-downloader#43]
This is what I see when I open `example/index.html` in Firefox:

![image](https://user-images.githubusercontent.com/1072292/144012203-16e00a50-b587-452a-84a2-713cd7c93984.png)

But perhaps that is because the file isn't online?

https://github.alessandropellizzari.it/test/apedesign-bg.png

**Comment by AleeeKoi** [comment]
HI @techieshark !
You are right, I forget to update the url in the example. Thank you :)
