### ISSUE TITLE
Multiple download and checking download status of each file

### ISSUE THREAD

**Issue by AdamReznicek** [AleeeKoi/js-file-downloader#44]
I need to download multiple files and show the status of eatch downloaded file... So i create `for` loop.
Is there any way to add to information into `process function` about file status HTML element?

thanks

**Comment by AleeeKoi** [comment]
Hi @AdamReznicek 
There is no way to download multiple file at now, your solution is correct. You need to create a process function for every download and then if you want to show something like the total download percentage you can calculate the mean of every running download.

**Comment by AdamReznicek** [comment]
@AleeeKoi Do you plan this feature in the future?

**Comment by AleeeKoi** [comment]
HI @AdamReznicek , nope. This feature is not in the road map.. but if you think it could be very useful (especially in your care) fell free to open a PR.
Thank you :)
