### ISSUE TITLE
Doesn't seem to work on mobile even if forceDesktopMode: true

### ISSUE THREAD

**Issue by cantonalex** [AleeeKoi/js-file-downloader#45]
![IMG_5917](https://user-images.githubusercontent.com/18063531/145501481-d956112c-eb05-4afe-bc15-75ef9ea00f47.jpg)

**Comment by AleeeKoi** [comment]
Hi @cantonalex thank you for the very useful screenshot..
Could you please recreate a test case on https://codesandbox.io/
Thank you

**Comment by cantonalex** [comment]
I couldn't determine if it was cloudflare or not but I solved the issue :)
