### ISSUE TITLE
onloadstart is request time or actual download start?

### ISSUE THREAD

**Issue by mjau-mjau** [AleeeKoi/js-file-downloader#48]
I have a case where I am downloading zip files compiled in real-time, which may require several seconds processing before server starts to output. In this case, I wanted to detect when the file actually starts to download, and I assumed I could do that with `onloadstart` event, but it seems this triggers as soon as the request is made? If so, perhaps it could be useful with `ondownloadstart`? Or am I missing something?

In the meantime, I am using the `process()` function to detect that `e.loaded > 0` but this seems less optimal.

**Comment by AleeeKoi** [comment]
Hello,
as you write `onloadstart` is fired when a request has started to load data. There is no `ondownloadstart` event available (here the complete events list https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest?retiredLocale=it#events).

You are doing it right using the `process` function. :)
