### ISSUE TITLE
ReferenceError: document is not defined

### ISSUE THREAD

**Issue by by3lish** [AleeeKoi/js-file-downloader#50]
## Error code :
/home/elish/Desktop/nodejs/node_modules/js-file-downloader/dist/js-file-downloader.js:1236
      var link = document.createElement('a');
                 ^

ReferenceError: document is not defined

**Comment by AleeeKoi** [comment]
This lib need to be used in an env that has some global variables (like window, document ecc). So you need a browser.
If not, this lib is not what you are searching for :)
