### ISSUE TITLE
Not downloading on chrome mobile

### ISSUE THREAD

**Issue by jacten** [AleeeKoi/js-file-downloader#51]
For whatever reason, this does not appear to work on chrome mobile on iOS. It seems to download, but nothing ends up in our files. I believe this used to work so possibly something changed on chrome. It works on safari. This is how we call the JsFileDownloader: 

```
new JsFileDownloader({
    forceDesktopMode: true,
    withCredentials: true,
    nativeFallbackOnError: true,
    headers: [
      {
        name: "timezoneOffset",
        value: new Date().getTimezoneOffset().toString(),
      },
    ],
    url: process.env.REACT_APP_API_URL + `${endpoint}?${stringify(params)}`,
```

**Comment by AleeeKoi** [comment]
wtf chrome! ... thanks @jacten for your feedback!
It could be great to add it as a feature, if you think possibile feel free to add a PR.
thank you, great job 🚀

**Comment by zsubzwary** [comment]
Guys is there any update on this ?

**Comment by AleeeKoi** [comment]
Hi @zsubzwary not yet!
