### ISSUE TITLE
Download files using HTTPS throw error on console

### ISSUE THREAD

**Issue by cfthody** [AleeeKoi/js-file-downloader#52]
I am using the latest version of this package minified for an internal project of the company I work and I noticed that when using HTTPS and trying to download files in different formats it throws an error on the console.
![vmconnect_C0xhse8b6L](https://user-images.githubusercontent.com/45386969/173610207-0f50cac4-5d08-49a9-80dd-99f4064535c0.png)
But this only happens on the first try, on the next's one the download proceeds correctly and no errors are shown.
Our source code that this happen is something like this
![vmconnect_OYNd3EWvOd](https://user-images.githubusercontent.com/45386969/173610481-a2e20dda-7bd7-499c-9bfa-03c53acbb3c5.png)
I enabled the nativeFallbackOnError to true and the error was
![vmconnect_NpbZhz3keL](https://user-images.githubusercontent.com/45386969/173611589-84235990-37fa-46ed-afae-a9ec17eec9cc.png)
So I tried debugging this function and also the endpoint and it seems that after returning the file to download it cannot be read and the `error.request.response` is null and the responseText is filled with `[Exception: DOMException: Failed to read the 'responseText' property from 'XMLHttpRequest': The value is only accessible if the object's 'responseType' is '' or 'text' (was 'arraybuffer').`
![vmconnect_ntIhnHOFTo](https://user-images.githubusercontent.com/45386969/173610917-82991a8e-08b9-4a9d-83bb-4337c27e6206.png)

**Comment by AleeeKoi** [comment]
Hi @cfthody , are you sure this issue is not related to backend problem?

**Comment by cfthody** [comment]
Yes, I'm sure. No error was found on the logs and also the BE was returning correctly the file(s) to download.
But I can confirm again and attach the necessary screenshots to reinforce my statement.

**Comment by cfthody** [comment]
Hii @AleeeKoi, sorry for the delay in answering.

I have done some tests again, and the BE is returning the array of bytes correctly.
If it helps I have put a breakpoint on the catch to check the error and is related to the minified version of the lib.

![UPJ8oNXWXM](https://user-images.githubusercontent.com/45386969/184831835-0635d33f-f3b0-469a-b927-8fcd274beb6e.png)

**Comment by AleeeKoi** [comment]
Hi @cfthody , no worry. Could you please recreate this issue on codesandbox.io and share it with me? Thanks
