### ISSUE TITLE
createObjectURL

### ISSUE THREAD

**Issue by shahind** [AleeeKoi/js-file-downloader#53]
When trying to use it in a Cordova-electron app I get this error:
Uncaught (in promise) TypeError: Failed to execute 'createObjectURL' on 'URL': Overload resolution failed.
    at t.<anonymous> (js-file-downloader.min.js:10)

(does not depend on the file type or server).

**Comment by AleeeKoi** [comment]
Hi @shahind , it's probably related to cordova electron.
This lib is born to support download in browser web app, the createObjectURL is part of the Web APIs.
I think you need to find a poly lib (or create it) to make this method available in your project.
Bye

**Comment by shahind** [comment]
Thanks @AleeeKoi, I'm trying to match it with Cordova, but should the type of `downloadedFile` be `URL`?, I guess it must be a `File`, `Blob`, or `MediaSource` even if you are working with Web APIs.

**Comment by shahind** [comment]
Thanks @AleeeKoi, Cordova uses Chromium or the internal browser, and as far as I checked, `createObjectURL` is available. The problem must be related to the type of `downloadedFile` which is `URL`, but it must be `File`, `Blob`, or `MediaSource`. Maybe a plugin has changed something. I'm working on it and will let you know if I find a solution.

**Comment by shahind** [comment]
Thanks @AleeeKoi

**Comment by shahind** [comment]
For any other person who faces this problem, there is no fix for this problem so far (see [related issue](https://github.com/apache/cordova-plugin-file/issues/316)) to fix the problem you need to save the `window.File` and `window.FileReader` before executing the Cordova for example in your `index.html` before `Cordova.js` script tag. You can re-assign them in the `mounted` function or you may change the `js-file-downloader` as I did by replacing `File` and `FileReader` with `originalFile` and `originalFileReader`.(sorry @AleeeKoi :)

**Comment by AleeeKoi** [comment]
Hi @shahind thanks for the feedback and the solution. 👍
