### ISSUE TITLE
Issue downloading a large file

### ISSUE THREAD

**Issue by TomRaz** [AleeeKoi/js-file-downloader#54]
Hello and thanks for this great library.

I'm having issues with a specific file, with is a large video (3.1GB), and stored on Amazon S3.
It seems that the file is being downloaded, I can see the progress through the `process` callback. 
Once the downloading is complete, the file is saved, but instead of the expected video file, there is a 4 bytes file, which is just a text file containing the string "null".

Any ideas?

Thanks,
Tom

**Comment by AleeeKoi** [comment]
Hi @TomRaz !
Thank you! 

It sounds very strange 🤔 
Could you recreate the problem on https://codesandbox.io/ ?

**Comment by TomRaz** [comment]
Sure!
There you go:
https://codesandbox.io/s/silly-waterfall-y6kr7p?file=/src/index.js

When opening the same video using the browser (chrome 108), and saving with "Save Video As", it downloads the file as expected.

**Comment by AleeeKoi** [comment]
Hi @TomRaz do you have a smaller file to test?
My internet connection requires some time to download.

Thanks

**Comment by TomRaz** [comment]
@AleeeKoi 
That's the thing, it only happens for larger files, like this one, I couldn't reproduce the issue with smaller files.

**Comment by AleeeKoi** [comment]
Ok, so I guess it's related probably to some kind of browser buffer/limit.
Does it only happen with Chrome? Have you found a threshold from which it stops working?
Thanks

**Comment by AleeeKoi** [comment]
Hi @TomRaz , doing a quick search seem there is a blob size limit (it depends by architecture, RAM, etc.)
When the download is completed, the JS try to create a blob object from the stream but it is too big to perform the store operations.

I'll look for a solution soon, thanks for your feedback 👍

**Comment by AleeeKoi** [comment]
Hi @TomRaz , sorry for the delay. Unluckily Blob is limited by browser or available RAM.
In your case, what I can suggest, is to switch to another lib like: https://github.com/jimmywarting/StreamSaver.js that create a worker to stream and store data directly in the FS.

**Comment by TomRaz** [comment]
> Hi @TomRaz , sorry for the delay. Unluckily Blob is limited by browser or available RAM. In your case, what I can suggest, is to switch to another lib like: https://github.com/jimmywarting/StreamSaver.js that create a worker to stream and store data directly in the FS.

OK, thank you for trying!
