### ISSUE TITLE
Add possibility to cancel download

### ISSUE THREAD

**Issue by vincesp** [AleeeKoi/js-file-downloader#55]
When downloading a large file, I show a progress bar with a cancel button in my UI.
Can you add a function to abort the download, i.e., call `abort()` on the underlying `request` object?

With this code, I can cancel the request, but the `finally` block is never being called, meaning the Promise never gets resolved.

``` js
async function downloadFile() {
  const activity = createActivity(props.file.fileName)
  try {
    const downloader = new JsFileDownloader({
      url: getUrlPath(props.file),
      timeout: 0,
      autoStart: false,
      process(event) {
        activity.determinate = event.lengthComputable
        if (!event.lengthComputable) return
        activity.update(event.loaded / event.total)
      },
    })
    activity.cancel = () => downloader.request.abort()
    await downloader.start()
  } finally {
    activity.remove()
  }
}
```

**Comment by AleeeKoi** [comment]
Hi @vincesp , so the await keep waiting.
I'll take a look asap. if you need it urgently fell free to send a PR.
Thanks

**Comment by AleeeKoi** [comment]
hi @vincesp , please take a look:
https://github.com/AleeeKoi/js-file-downloader#abort
