### ISSUE TITLE
Refused to get unsafe header "Content-Disposition"

### ISSUE THREAD

**Issue by HollPapazian** [AleeeKoi/js-file-downloader#57]
In react I get this error \ Refused to get unsafe header "Content-Disposition". 
From line: let content = this.request.getResponseHeader('Content-Disposition');

**Comment by akshat-angelone057** [comment]
pass file name also in the object parameter for ex - 

`new JsFileDownloader({
					url: 'url,
					filename: 'hello.pdf',
				});`

**Comment by AleeeKoi** [comment]
Hi @HollPapazian , If there are errors related to other frameworks I can't do anything.
This lib just read the http response header, check if you are not using a secure encrypted connection.
In other case you can set a custom name like suggested by @akshat-angelone057
