### ISSUE TITLE
issue trying to download remote files

### ISSUE THREAD

**Issue by inglesuniversal** [AleeeKoi/js-file-downloader#8]
Your script is awesome for downloading files that are hosted in the same server or directory

however, I had CORS related issues since most of the files I have are stored inside buckets provided by Google Cloud Platform, with an entirely different url path.

Is there a way to accomplish that with JS or make adjustments to the script itself.

Thanks

and STAY SAFE

**Comment by AleeeKoi** [comment]
Hi @inglesuniversal 
Thank you for your message.

Unfortunately cross-origin is a known limit, to resolve you need to enable CORS on the server providing the resource or creating a proxy (for example in PHP or node.js) on the same domain as the js-file-downloader script.

In your case, having to download from google drive, you cannot enable CORS on the target server.

**Comment by AleeeKoi** [comment]
Hi @inglesuniversal I'm closing this issue, let me know if you need more support.
