### ISSUE TITLE
Doesn't work on mobile browsers

### ISSUE THREAD

**Issue by takosunil** [AleeeKoi/js-file-downloader#9]
It's working fine with desktop browsers. But doesn't work on mobile browsers.

Do you have solution or any workaround for mobile browsers?

Thanks in advance.

**Comment by takosunil** [comment]
For mobile browsers, instead of downloading file, it opens in new tab

**Comment by AleeeKoi** [comment]
Hi @takosunil 
There is an option to enable this lib on mobile devices.
By default is disabled on mobile and works as you have described (opening new tab etc.).

Have you tried to enable ```forceDesktopMode``` setting it to ```true```?

**Comment by takosunil** [comment]
Thanks @AleeeKoi, it working. 👍
